In [63]:
import pandas as pd

medals = pd.read_csv('data/olympic_medals.csv')
print(medals.columns.tolist())
print(medals.dtypes)
medals.head()

['season', 'year', 'medal', 'country_code', 'country', 'games', 'sport', 'event_gender', 'event_name']
season          object
year             int64
medal           object
country_code    object
country         object
games           object
sport           object
event_gender    object
event_name      object
dtype: object

,season,year,medal,country_code,country,games,sport,event_gender,event_name
0,Summer,1896,Gold,USA,United States,1896 Athens,Athletics,Men's,100m
1,Summer,1896,Silver,GER,Germany,1896 Athens,Athletics,Men's,100m
2,Summer,1896,Bronze,HUN,Hungary,1896 Athens,Athletics,Men's,100m
3,Summer,1896,Bronze,USA,United States,1896 Athens,Athletics,Men's,100m
4,Summer,1896,Gold,USA,United States,1896 Athens,Athletics,Men's,400m

In [64]:
gdp = pd.read_csv('data/API_NY.GDP.MKTP.CD_DS2_en_csv_v2_94769.csv', skiprows=4)  # 4 first line are not data 

# transform column format to row format 
gdp_long = gdp.melt(
    id_vars=['Country Name', 'Country Code'],
    value_vars=[str(y) for y in range(1960, 2025)],
    var_name='Year',
    value_name='GDP'
)

gdp_long = gdp_long.dropna(subset=['GDP'])

gdp_long['Year'] = gdp_long['Year'].astype(int)
gdp_long = gdp_long[(gdp_long["Year"] <= 2016)]

gdp_long.sort_values(by= "Year") # to see when it starts (1960)
print(gdp_long.dtypes)
gdp_long.head()

Country Name     object
Country Code     object
Year              int64
GDP             float64
dtype: object

                   Country Name Country Code  Year           GDP
1   Africa Eastern and Southern          AFE  1960  2.420569e+10
3    Africa Western and Central          AFW  1960  1.190481e+10
9                     Argentina          ARG  1960  1.586547e+10
13                    Australia          AUS  1960  1.863568e+10
14                      Austria          AUT  1960  6.624086e+09

In [65]:
medals = medals[medals['year'] >= 1960]  
medals['year'] = medals['year'].astype(int)

In [ ]:
# try to merge (maybe after)