In [16]:
import pandas as pd

df = pd.read_csv('../data/medals_merged_gdp_capita_log_max.csv')
df["inv_gdp_usd"] = 1 / df["gdp_usd"]
df.head()

,season,year,medal,country_code,country,games,sport,event_gender,event_name,Country Code,gdp_usd,inv_gdp_usd
0,Summer,1960,Gold,EUA,Unified Team of Germany,1960 Rome,Athletics,Men's,100m,DEU,0.881554,1.134361
1,Summer,1960,Silver,USA,United States,1960 Rome,Athletics,Men's,100m,USA,1.000000,1.000000
2,Summer,1960,Bronze,GBR,Great Britain,1960 Rome,Athletics,Men's,100m,GBR,0.904599,1.105463
3,Summer,1960,Gold,ITA,Italy,1960 Rome,Athletics,Men's,200m,ITA,0.840550,1.189698
4,Summer,1960,Silver,USA,United States,1960 Rome,Athletics,Men's,200m,USA,1.000000,1.000000

In [24]:
inv_gdp_by_country = df.groupby('country')['inv_gdp_usd'].agg(inv_gdp_usd_mean='mean', medals='count')
inv_gdp_by_country

                             inv_gdp_usd_mean  medals
country
AIN                                       NaN       0
Afghanistan                          1.955718       2
Albania                              1.345986       2
Algeria                              1.471076      20
Argentina                            1.305991      42
...                                       ...     ...
Virgin Islands, US                        NaN       0
Yugoslavia                                NaN       0
Yugoslavia Federal Republic          1.523266       7
Zambia                               1.813149       3
Zimbabwe                             1.963784       8

[166 rows x 2 columns]

In [26]:
inv_gdp_by_country.sort_values("inv_gdp_usd_mean", ascending=False).head(10)

             inv_gdp_usd_mean  medals
country
Burundi              2.264878       2
Ethiopia             2.072989      62
Mozambique           2.022357       2
Zimbabwe             1.963784       8
Afghanistan          1.955718       2
Eritrea              1.938004       1
Niger                1.935121       2
Uganda               1.890723      13
Togo                 1.858857       1
Pakistan             1.841043      10

In [27]:
# save inv_gdp_by_country to ../website/public/efficiency_by_country.csv
inv_gdp_by_country.to_csv('../website/public/efficiency_by_country.csv')